### ISSUE TITLE
PMID: 17264077	Dynamic developmental elaboration of N-linked glycan complexity in the Drosophila melanogaster embryo

### ISSUE THREAD

**Issue by Mindyporterfield** [glygener/glygen-issues#399]
[Fly-N-paper](https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Paper%20Curation/PMID%C2%A017264077%20Fly-N?csf=1&web=1&e=8HPrTO)

**Tasks for Anh**
* #414 

**Tasks for Sena**

**Tasks for Mindy**

**Comment by Mindyporterfield** [comment]
Good morning,
Please start with [Fly-N-077 paper](https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Paper%20Curation/PMID%C2%A017264077%20Fly-N?csf=1&web=1&e=EACW7c)

FIGURE 4. TheN-linked glycan profile of wild-typeDrosophila embryos.

Draw the glycans, they are free end (not reduced)

I added an [example gws file](https://gwu0.sharepoint.com/:u:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Paper%20Curation/PMID%C2%A017264077%20Fly-N/FlyN-examples.gws?csf=1&web=1&e=pjaH22)
to be used in Grits

**Comment by Mindyporterfield** [comment]
- [x] Mindy- read paper, id data to be curated (which figures etc), draw an example structure paying attention to reducing end type (free or reduced) and modifications (permethylation). Write a ticket for Anh and link example structure.
- 
- [x] Anh-Draw assigned structures using GRITS, export as gws file and put in the corresponding folder in sharepoint, comment in github to let me know its done.

- [x] Mindy-check structures, give any needed feedback

- Mindy -proceed with the rest of the curation workflow

- @senaarpinar [ ] -convert structures (Sena) and get glytoucan ids [Fly-GWS](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=EACW7c&cid=aba533af%2Dff65%2D4b17%2D8c9a%2D5c21f48836db&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC&id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FPaper%20Curation%2FPMID%C2%A017264077%20Fly%2DN%2FGWS&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132)
- [x] -verify structures match glytoucan structure
- [x] -Fill in remaining info for species, etc https://docs.google.com/document/d/1QPWU29l6pzo8bKIQ6epEidPDDxyp-5JQk9drhS-zJOg/edit#heading=h.urs6nll5b27n
- [x] -deposit in sharepoint and comment on ticket

**Comment by senaarpinar** [comment]
generated the [excel sheet](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B8705EAF0-94EC-47F3-943A-BEA839E356DC%7D&file=Glycans-Jul062023.xlsx&action=default&mobileredirect=true) with glytoucan ids

**Comment by senaarpinar** [comment]
uploaded a new version of the excel file (after rerunning with Rene's changes to handle structures with brackets)

**Comment by Mindyporterfield** [comment]
reviewed structures and filled in remaining columns on spreadsheet (separate tab)
complete except no functional annotations found,

@mtiemeyer0919 what functional annotation do you suggest for the fly N-linked paper?
here is the current list, you can add terms if needed

For Functional annotation use the following (non-comprehensive) dictionary: 

    adhesion 
    homing 
    inflammation 
    protein targeting 
    protein secretion 
    protein stability 
    protein folding 
    ER stress 
    protein degradation 
    circulating half-life 
    clearance 
    internalization 
    metastasis 
    shielding 
    recognition 
    toxin receptor 
    viral receptor 
    microbial receptor 
    receptor signaling 
    sperm maturation 
Added terms (Mike)
differentiation
biomarker

**Comment by Mindyporterfield** [comment]
data is in  [sharepoint folder](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=EACW7c&cid=aba533af%2Dff65%2D4b17%2D8c9a%2D5c21f48836db&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC&id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FPaper%20Curation%2FPMID%C2%A017264077%20Fly%2DN&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132)  [excel sheet](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B40641BC1-F538-4CDB-945D-AF36D96F5F35%7D&file=Glycans-17264077-flyN-complete.xlsx&action=default&mobileredirect=true)

I will go over with @mtiemeyer0919 and then let @ReneRanzinger know its ready 
use the tab 3-Final Glygen for data upload

**Comment by Mindyporterfield** [comment]
@ReneRanzinger The fly n linked excel is ready in sharepoint.
there are 4 sets of data (4 tabs that are named 3-final glygen...)
The only thing is there is a duplicate column that needs to be removed once jeet replies about where he wants it (he accidentally left 2 copies of 1 column) see  #622

**Comment by ReneRanzinger** [comment]
@Mindyporterfield we talked about having a single sheet that my program can detect with a fixed name. That is missing. I also noticed that in the tollo sheet it has "tollo-" in the Variant column. Is that a typo? Also the contributor column only has you mentioned. Was that done without Ain?

**Comment by Mindyporterfield** [comment]
I will fix it
tollo- is how tollo minus is written as a gene that is missing as stated in the paper, let me check with mike if I can write as tollo, does - cause a problem? i couls also spell it out if so
i will combine the tabs  or make separate files
and add anh (i totally missed that)

thanks

--------------------------------------------------
Melody Porterfield, Ph.D.
CCRC UGA
Senior Research Associate
***@***.***
________________________________

**Comment by Mindyporterfield** [comment]
@ReneRanzinger I am still not sure about the contributor column, we will need to see what come out of the meeting wednesday. otherwise you can give it a try. The tab name is Final-GlyGen

**Comment by Mindyporterfield** [comment]
the  [fly n-linked structures excel](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B40641BC1-F538-4CDB-945D-AF36D96F5F35%7D&file=Glycans-17264077-flyN-complete.xlsx&action=default&mobileredirect=true) ready @ReneRanzinger The tab name is Final-GlyGen

**Comment by Mindyporterfield** [comment]
the [fly n-linked structures excel](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B40641BC1-F538-4CDB-945D-AF36D96F5F35%7D&file=Glycans-17264077-flyN-complete.xlsx&action=default&mobileredirect=true) ready @ReneRanzinger The tab name is Final-GlyGen
